name: my_tube
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  cloud_firestore: ^5.2.0
  firebase_core: ^3.3.0
  http: ^1.2.2
  carousel_slider: ^5.0.0  # Updated dependency version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/rongrende.JPG
